name: Deploy Surveilr Application

on:
  push:
    branches:
      - main  # Trigger deployment on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Docker image
      run: |
        docker build -t ghcr.io/${{ github.repository }}/surveilr-app:latest .

    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image to GHCR
      run: |
        docker push ghcr.io/${{ github.repository }}/surveilr-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: SSH into the server
      uses: appleboy/ssh-action@v0.1.1
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Pull the latest Docker image from GHCR
          docker pull ghcr.io/${{ github.repository }}/surveilr-app:latest

          # Stop the currently running container if it exists
          docker ps -q -f name=surveilr-runtime | xargs -r docker stop

          # Remove the old container
          docker ps -a -q -f name=surveilr-runtime | xargs -r docker rm

          # Run the new container using Docker Compose
          docker-compose up -d
